// Zero-dependency stand-in build (see hello-js/gen.js). Demonstrates the
// workspace dependency edge: this package builds AFTER @scope/hello-js and
// its generated code requires the sibling's product at runtime.
const fs = require("fs");
const path = require("path");
const sibling = path.join(__dirname, "..", "hello-js", "dist", "index.js");
const hello = require(sibling);
fs.mkdirSync(path.join(__dirname, "dist"), { recursive: true });
fs.writeFileSync(
    path.join(__dirname, "dist", "index.js"),
    "// generated by hello-ts gen.js\n" +
    "module.exports.greet = () => require(\"../../hello-js/dist/index.js\").hello();\n");
console.log("hello-ts: dist/index.js written (workspace edge resolved: " +
    hello.hello() + ")");
