// The C++ consumer: the repo's first real C++ executable against a
// cxx-generated bridge. Includes the GENERATED header (the bridge surface)
// plus the hand-written C++-side header, calls Rust, lets Rust call back.
#include <cstdio>
#include "bridge.h"   // generated by polyorch_rust_cxxbridge (the
                         // quoted form: the include dir layer carrying it
                         // is spelled by CMake below, since the generated
                         // tree root carries the fusion prefix when fused)
#include "bridge_impl.h"              // hand-written C++ side (host_scale)

int main() {
    // C++ -> Rust (the bridge surface is global-namespace: cxx emits it
    // there because the bridge module has no namespace attribute)
    rust::String echoed = spine_echo("c++ app");
    std::int64_t sum = spine_add(20, 22);
    // Rust -> C++ (the bridge calls host_scale back into this binary)
    double scaled = host_scale(6.0, 7.0);
    std::printf("%s; spine_add = %lld; host_scale(6,7) = %.1f\n",
                echoed.c_str(), static_cast<long long>(sum), scaled);
    return 0;
}
