
function(polyorch_parse_all_arguments prefix type options one_value_args multi_value_args)
    # Mirrors polyorch macro: (result type options oneValueArgs multiValueArgs)
    cmake_parse_arguments(${prefix} "${options}" "${one_value_args}" "${multi_value_args}" ${ARGN})
    set(${prefix}_UNPARSED_ARGUMENTS "${${prefix}_UNPARSED_ARGUMENTS}" PARENT_SCOPE)
    foreach(option ${options})
        set(${prefix}_${option} "${${prefix}_${option}}" PARENT_SCOPE)
    endforeach()
    foreach(multi_option ${multi_value_args})
        set(${prefix}_${multi_option} "${${prefix}_${multi_option}}" PARENT_SCOPE)
    endforeach()
    foreach(single_option ${one_value_args})
        set(${prefix}_${single_option} "${${prefix}_${single_option}}" PARENT_SCOPE)
    endforeach()
endfunction()
