
function(polyorch_parse_all_arguments prefix type options one_value_args multi_value_args)
    # Mirrors octk macro: (result type options oneValueArgs multiValueArgs)
    cmake_parse_arguments(${prefix} "${options}" "${one_value_args}" "${multi_value_args}" ${ARGN})
    set(${prefix}_UNPARSED_ARGUMENTS "${${prefix}_UNPARSED_ARGUMENTS}" PARENT_SCOPE)
    foreach(option ${options})
        set(${prefix}_${option} "${${prefix}_${option}}" PARENT_SCOPE)
    endforeach()
    foreach(multi_option ${multi_value_args})
        set(${prefix}_${multi_option} "${${prefix}_${multi_option}}" PARENT_SCOPE)
    endforeach()
    foreach(single_option ${one_value_args})
        set(${prefix}_${single_option} "${${prefix}_${single_option}}" PARENT_SCOPE)
    endforeach()
endfunction()

# Evaluate a CMake boolean expression, supporting variables, NOT/AND/OR.
# Space-separated operators (DEPENDS "A AND B") arrive as ONE argument; if(${expr})
# would then receive a single space-containing string (evaluated as a variable name →
# always false). Splitting on spaces turns it into a proper argument list for if().
function(polyorch_evaluate_expression result)
    if(NOT "${ARGN}" STREQUAL "")
        set(expression "${ARGN}")
    else()
        set(expression "${result}")
    endif()
    string(REPLACE " " ";" expression "${expression}")
    if(${expression})
        set(${result} ON PARENT_SCOPE)
    else()
        set(${result} OFF PARENT_SCOPE)
    endif()
endfunction()

function(polyorch_option variable description value)
    polyorch_parse_all_arguments(arg
        "polyorch_option"
        ""
        ""
        "DEPENDS;EMIT_IF;SET;SET_NEGATE;OR_CONDITION;VERIFY" ${ARGN})
    polyorch_evaluate_expression(result ${value})
    if("${arg_EMIT_IF}" STREQUAL "")
        set(emit_if ON)
    else()
        polyorch_evaluate_expression(emit_if ${arg_EMIT_IF})
    endif()
    if("${arg_OR_CONDITION}" STREQUAL "")
        set(or_condition OFF)
    else()
        polyorch_evaluate_expression(or_condition ${arg_OR_CONDITION})
    endif()
    set(input OFF)
    # If INPUT_ is defined trying to use INPUT_ variable to enable/disable option.
    if((DEFINED "INPUT_${variable}")
            AND (NOT "${INPUT_${variable}}" STREQUAL "undefined")
            AND (NOT "${INPUT_${variable}}" STREQUAL ""))
        set(input ON)
        if(INPUT_${variable})
            set(input_result ON)
        else()
            set(input_result OFF)
        endif()
    elseif(or_condition)
        set(input ON)
        set(input_result ON)
    endif()
    # Warn about an option which is not emitted, but the user explicitly provided a value for it.
    if(input)
        if(emit_if)
            set(result ${input_result})
        else()
            message(WARNING "Option ${variable} is not emitted, but the user explicitly provided a value for it.")
        endif()
    endif()
    # Evaluate depends result
    if("${arg_DEPENDS}" STREQUAL "")
        set(depends_result ON)
    else()
        polyorch_evaluate_expression(depends_result ${arg_DEPENDS})
    endif()
    if(${depends_result})
        if(input AND emit_if)
            # Forced state: INPUT_ injection / OR_CONDITION in effect — GUI greyed out (intentional).
            unset(${variable} CACHE)
            set(${variable} "${result}" CACHE STRING "${description}" FORCE)
            set(_option_string_type_if_cache_${variable} ON CACHE INTERNAL "${description}" FORCE)
        else()
            # Normal state: user-editable BOOL checkbox (no FORCE). Clear any forced STRING residue first.
            if(${_option_string_type_if_cache_${variable}})
                unset(${variable} CACHE)
            endif()
            set(${variable} ${result} CACHE BOOL "${description}")
            set(_option_string_type_if_cache_${variable} OFF CACHE INTERNAL "${description}" FORCE)
            set(result ${${variable}})
        endif()
    else()
        # Depends failed: greyed out with an explanatory value (OpenCTK behavior).
        # Warn whenever the desired value was ON — the default (result) OR a user/cache
        # request — so clamped-to-OFF switches are visible in configure output (Momus F4).
        if(${result})
            message(WARNING "Option ${variable} is depends on ${arg_DEPENDS}.")
        elseif(${variable})
            # -D (cache) request for ON: still clamped. The FORCE below hasn't run yet,
            # so the cache still holds the user's ON — surface it (Momus F4).
            message(WARNING "Option ${variable} requested ON but clamped OFF: depends on ${arg_DEPENDS}.")
        endif()
        set(${variable} "OFF" CACHE STRING "${description} depends on ${arg_DEPENDS}!" FORCE)
        set(_option_string_type_if_cache_${variable} ON CACHE INTERNAL "${description}" FORCE)
        set(result OFF)
    endif()
    if(${variable})
        message(STATUS "${variable}: ON")
    else()
        message(STATUS "${variable}: OFF")
    endif()
    set(${variable} ${result} PARENT_SCOPE)
endfunction()
