// Zero-dependency build script: the stand-in for the real thing (tsc/vite
// would live here in a real package -- PolyOrch never invokes them; the
// scripts ARE the build, adjudication 4). Emits the dist product.
const fs = require("fs");
const path = require("path");
fs.mkdirSync(path.join(__dirname, "dist"), { recursive: true });
fs.writeFileSync(
    path.join(__dirname, "dist", "index.js"),
    "// generated by hello-js gen.js\nmodule.exports = { hello: () => \"hello from hello-js\" };\n");
console.log("hello-js: dist/index.js written");
